### ISSUE TITLE
Add minimal working example for both renderers

### ISSUE THREAD

**Issue by leleogere** [jaynewey/bubbles#2]
It would be a great addition to add to the README a minimal working example (ideally for both renderers). I'm struggling to reproduce the examples using the provided jsons.

**Comment by jaynewey** [comment]
This works for me:

```
pip install pillow
```

```py
from PIL import Image, ImageDraw
from pathlib import Path

from bubbles.emitter import Emitter
from bubbles.particle import Particle
from bubbles.particle_effect import ParticleEffect
from bubbles.renderers.image_effect_renderer import ImageEffectRenderer

EXAMPLE_FILE = "tornado"
EXAMPLE_DIR = "examples/"
IMG_DIR = "out/" + EXAMPLE_FILE + "/"

r = ImageEffectRenderer()

# load example json
with open(EXAMPLE_DIR + EXAMPLE_FILE + ".json") as f:
    import json
    pe = json.load(f)
particle_effect = ParticleEffect.load_from_dict(pe)

# align the effect in the frame
particle_effect.x, particle_effect.y = 60, 128

r.register_effect(particle_effect)

Path(IMG_DIR).mkdir(parents=True, exist_ok=True)
for i in range(240):
    particle_effect.update()
    if i > 0:
        image = Image.new("RGB", (128, 128), (0, 0, 0, 255))
        r.render_effect(particle_effect,  image)

        image.save(IMG_DIR + str(i) + ".png")
```

It will create a directory at `./out/tornado` with all the frames of the animation. You can then compile this into a gif or video with [`imageio`](https://github.com/imageio/imageio) or otherwise.

As for PyGame, I haven't touched this in 2 years and PyGame 2 has since came out - doesn't seem to be working for me either but I'm afraid I don't have much time to look into why at the moment :(

Let me know if it works for you I'll add it to the README.

**Comment by leleogere** [comment]
Yes thank you I managed to get it to work!

I was missing the part to align the effect in the frame (I couldn't understand why it seemed only to print something at the top left of the screen). If you add that to the README, maybe replace that line with `particle_effect.set_pos` as it seems to do that exactly (I don't know how I missed it).

No problem for PyGame, I only need PIL anyway. However, it might be worth specifying in the README that this renderer does not work with recent versions of PyGame.

One last question, I'm not sure to understand the point of `r.register_effect(particle_effect)`. It seems that the script you sent works without it.

**Comment by jaynewey** [comment]
Glad to see it's working!

> One last question, I'm not sure to understand the point of r.register_effect(particle_effect). It seems that the script you sent works without it.

`EffectRenderer.register_effect` ensures all of the textures required for the effect are loaded. However for the tornado effect, no textures are needed. It's only really useful for stuff like the hearts example where a texture is used.

**Comment by leleogere** [comment]
Ok got it, thank you!
